"""Add unique constraint to user_id and book_title in saved_books table

Revision ID: 3df4e1c12d09
Revises: 3fcea2efcd0e
Create Date: 2024-04-14 17:24:52.874464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3df4e1c12d09'
down_revision = '3fcea2efcd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('saved_books', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_book', ['user_id', 'book_title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_books', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_book', type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
