"""Add publisher relationship to Books

Revision ID: 88090e05cefd
Revises: ef7f02ec2f7f
Create Date: 2023-11-20 18:20:48.845290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88090e05cefd'
down_revision = 'ef7f02ec2f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('books_genre_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publishers', ['publisher_id'], ['id'])
        batch_op.drop_column('genre_id')

    with op.batch_alter_table('saved_books_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_saved', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_books_association', schema=None) as batch_op:
        batch_op.drop_column('cover_url')
        batch_op.drop_column('date_saved')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('books_genre_id_fkey', 'genres', ['genre_id'], ['id'])
        batch_op.drop_column('publisher_id')

    op.create_table('genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genres_pkey')
    )
    # ### end Alembic commands ###
